In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from numpy import array
from sklearn.metrics import accuracy_score
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix

In [2]:
train = pd.read_csv ("C:\\Users\\ANSHUMAN\\Desktop\\ML\\Titanic Dataset\\train.csv")
test = pd.read_csv ("C:\\Users\\ANSHUMAN\\Desktop\\ML\\Titanic Dataset\\test.csv")

In [3]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 66.2+ KB


In [5]:
del train['Cabin']
del test ['Cabin']

In [6]:
train=train.dropna(subset = ['Age', 'Embarked'])

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 11 columns):
PassengerId    712 non-null int64
Survived       712 non-null int64
Pclass         712 non-null int64
Name           712 non-null object
Sex            712 non-null object
Age            712 non-null float64
SibSp          712 non-null int64
Parch          712 non-null int64
Ticket         712 non-null object
Fare           712 non-null float64
Embarked       712 non-null object
dtypes: float64(2), int64(5), object(4)
memory usage: 55.6+ KB


In [8]:
import matplotlib.pyplot as plt
x=train["Survived"].value_counts()
y=["Died","Survived"]
plt.bar (y[0],x[0],label = "Died",align = "center" )
plt.bar (y[1],x[1],label = "Alive",align = "center")
plt.legend()
plt.ylabel ("No. of People")
plt.xlabel ("Died/Survived")
plt.show()

In [9]:
train = train.drop (columns=['Name'])

In [10]:
train = train.drop (columns=['PassengerId'])

In [11]:
train = train.drop (columns=['Ticket'])

In [12]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 8 columns):
Survived    712 non-null int64
Pclass      712 non-null int64
Sex         712 non-null object
Age         712 non-null float64
SibSp       712 non-null int64
Parch       712 non-null int64
Fare        712 non-null float64
Embarked    712 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 44.5+ KB


In [13]:
train_dummies = pd.get_dummies (train)
train_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 11 columns):
Survived      712 non-null int64
Pclass        712 non-null int64
Age           712 non-null float64
SibSp         712 non-null int64
Parch         712 non-null int64
Fare          712 non-null float64
Sex_female    712 non-null uint8
Sex_male      712 non-null uint8
Embarked_C    712 non-null uint8
Embarked_Q    712 non-null uint8
Embarked_S    712 non-null uint8
dtypes: float64(2), int64(4), uint8(5)
memory usage: 42.4 KB


In [14]:
X = train_dummies.iloc[:, [1,2,3,4,5,6,7,8,9,10]].values
Y = train_dummies.iloc[:, [0]].values

In [15]:
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.1, random_state = 0)

In [16]:
sc_X = StandardScaler()
X_Train = sc_X.fit_transform(X_Train)
X_Test = sc_X.transform(X_Test)

In [17]:
classifier = RandomForestClassifier(n_estimators = 80, criterion = 'entropy', max_depth = 6)
classifier.fit(X_Train,Y_Train)

c:\users\anshuman\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=6, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=80, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [18]:
Y_Pred = classifier.predict(X_Test)

In [19]:
Y_Pred

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1], dtype=int64)

In [20]:
cm = confusion_matrix(Y_Test, Y_Pred)

In [21]:
cm

array([[36,  6],
       [ 9, 21]], dtype=int64)

In [22]:
test = pd.read_csv ("C:\\Users\\ANSHUMAN\\Desktop\\ML\\Titanic Dataset\\test.csv")
test = test.drop (columns=['Name'])
test = test.drop (columns=['PassengerId'])
test = test.drop (columns=['Ticket'])
test = test.drop (columns=['Cabin'])

In [23]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
Pclass      418 non-null int64
Sex         418 non-null object
Age         418 non-null float64
SibSp       418 non-null int64
Parch       418 non-null int64
Fare        418 non-null float64
Embarked    418 non-null object
dtypes: float64(2), int64(3), object(2)
memory usage: 19.6+ KB


In [24]:
test_dummies = pd.get_dummies (test)
test_dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
Pclass        418 non-null int64
Age           418 non-null float64
SibSp         418 non-null int64
Parch         418 non-null int64
Fare          418 non-null float64
Sex_female    418 non-null uint8
Sex_male      418 non-null uint8
Embarked_C    418 non-null uint8
Embarked_Q    418 non-null uint8
Embarked_S    418 non-null uint8
dtypes: float64(2), int64(3), uint8(5)
memory usage: 18.4 KB


In [25]:
X = test_dummies.iloc[:, [0,1,2,3,4,5,6,7,8,9]].values
test1 = pd.read_csv ("C:\\Users\\ANSHUMAN\\Desktop\\ML\\Titanic Dataset\\gender_submission.csv")
Y = test1.iloc[:, [1]].values

In [26]:
sc_X = StandardScaler()
X_Test = sc_X.fit_transform(X)

In [27]:
Y_Pred = classifier.predict(X_Test)

In [28]:
cm = confusion_matrix(Y, Y_Pred)

In [29]:
cm

array([[253,  13],
       [ 22, 130]], dtype=int64)

In [30]:
np.savetxt("C:\\Users\\ANSHUMAN\\Desktop\\ML\\Titanic Dataset\\submission2.csv",Y_Pred, delimiter=',', header="A")

In [31]:

accuracy_score(Y, Y_Pred)

0.916267942583732